apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox
      command:
        - env
      resources:
        requests:
          memory: "256Mi"
          cpu: "1"
        limits:
          memory: "256Mi"
          cpu: "1"
